#!/bin/bash
if [ "$1" != "--run" ]; then
	echo "Error: This script should be run via ansible, not directly. Exiting..."
	exit 1
fi
exec 2>&1

echo
echo "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv $(hostname -s)"
echo Hello
rm -f /root/runonce.sh /tmp/runonce.sh

echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ $(hostname -s)"


