#!/usr/bin/env ansible-playbook
---
- hosts: all
  gather_facts: False

  tasks:
    - name: Install latest version of packages
      yum: name={{ item }} state=latest
      with_items:
        - vim-enhanced
        - strace
  
 

