---
- name: Transfer and execute a script.
  hosts: all
  tasks:
     - name: Transfer the script
       copy: src=../scripts/runonce/script dest=/root/runonce.sh mode=0700

     - name: Execute the script
       command: sh /root/runonce.sh --run

