#!/usr/bin/env ansible-playbook
---
- name: Add bunch of users
  hosts: all
  gather_facts: False

  vars_files:
   - ../vars/users.yml

  tasks: 
   - user: name={{ item.key }} comment={{ item.value.realname }}
     with_dict: "{{ users }}"

   - authorized_key: user={{ item.key }} key={{ item.value.key }}
     with_dict: "{{ users }}"

#   - user: name={{ item.key }} state=absent remove=yes
#     with_dict: "{{ users }}"


  
 

